# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-het-anant"
BBFILE_PATTERN_meta-het-anant = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-het-anant = "20"

LAYERDEPENDS_meta-het-anant = "core"
LAYERSERIES_COMPAT_meta-het-anant = "scarthgap"
